# Generated by Django 4.0.5 on 2022-09-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="sent_from",
            field=models.EmailField(default="bansheenoreply@gmail.com", max_length=254),
        ),
    ]
