# Generated by Django 4.0.5 on 2022-09-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_alter_email_sent_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="sent_from",
            field=models.EmailField(max_length=254),
        ),
    ]
