# Generated by Django 4.0.5 on 2022-11-24 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_trainingsetting_allow_senior_assignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorizedEmail',
        ),
    ]
