# Generated by Django 4.0.5 on 2022-11-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_authorizedusername"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorizedusername",
            name="username",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
