# Generated by Django 4.0.5 on 2022-08-11 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="senior",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="senior",
            name="lastname",
        ),
        migrations.AlterField(
            model_name="senior",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
