# Generated by Django 4.0.5 on 2022-09-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teach",
            options={"ordering": ["teach_id"]},
        ),
        migrations.RenameField(
            model_name="teach",
            old_name="lesson_id",
            new_name="teach_id",
        ),
    ]
