# Generated by Django 4.0.5 on 2022-09-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_alter_senior_permission_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="senior",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
