# Generated by Django 4.0.5 on 2022-09-19 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0003_senior_email_confirmed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="level",
            options={"ordering": ["name"]},
        ),
    ]
