# Generated by Django 4.0.5 on 2022-10-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0005_genericlesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="senior",
            name="discluded_assignment",
            field=models.BooleanField(default=False),
        ),
    ]
