# Generated by Django 4.0.5 on 2022-11-24 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0006_senior_discluded_assignment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="senior",
            name="email_confirmed",
        ),
    ]
