# Generated by Django 4.0.5 on 2022-11-24 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_remove_senior_email_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='senior',
            options={'ordering': ['level']},
        ),
        migrations.RemoveField(
            model_name='senior',
            name='rank',
        ),
    ]
